version: "3"

services:
  web:
    build: .
    container_name: courses
    command:
      bash -c "python manage.py makemigrations && 
               python manage.py migrate && 
               python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      -  .env
#    depends_on: :
#    -  db
  redis:
    image: redis:alpine
#    depends_on: :
#    -  db

  celery-beat:
    restart: always
    build:
      context: .
    command:
      bash -c "celery -A courses beat -l info"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - web
#      - db


  celery-worker:
    restart: always
    build:
      context: .
    command:
      bash -c "celery -A courses worker -pool=solo -l  info"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - web
      - celery-beat
#      - db

#db:
#    image: postgres
#    volumes:
#     - .:/app