# Generated by Django 3.2.18 on 2023-03-20 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profileuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.role'),
            preserve_default=False,
        ),
    ]
