# Generated by Django 3.2.18 on 2023-03-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profileuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='course_finished',
            field=models.ManyToManyField(blank=True, related_name='course_finished', to='core.Course'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='lecture_finished',
            field=models.ManyToManyField(blank=True, related_name='lecture_finished', to='core.Lecture'),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='stunden_course', to='core.Course'),
        ),
    ]
