# Generated by Django 3.2.18 on 2023-03-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230320_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='student_course', to='core.Course'),
        ),
    ]
