# Generated by Django 3.2.18 on 2023-04-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_profileuser_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='massage',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
