# Generated by Django 3.2.18 on 2023-04-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_comment_massage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='massage',
            new_name='message',
        ),
    ]
